/**
 * Ads Intake Mock Service
 * Generates sample leads from Meta Ads, Google Ads, and TikTok.
 */

export const getMockAdsLeads = () => [
    { id: 'l1', externalLeadId: 'meta_01', name: 'John Doe', email: 'john@example.com', phone: '+90 532 000 0001', leadSource: 'Meta Ads', campaignName: 'Bodrum Luxury 2024', adSetName: 'UK Expats', adId: 'ad_01', formId: 'f_01', status: 'new', time: '10 dk önce', createdAt: '2026-01-27T22:00:00Z', region: 'Bodrum', propertyType: 'Villa', budget: 500000, currency: 'GBP', utm_source: 'fb', utm_medium: 'paid', utm_campaign: 'luxury', consentKvkk: true },
    { id: 'l2', externalLeadId: 'google_01', name: 'Sarah Smith', email: 'sarah@gmail.com', phone: '+44 7700 900123', leadSource: 'Google Ads', campaignName: 'Search - Kyrenia', adSetName: 'General', adId: 'ad_02', formId: 'f_02', status: 'new', time: '1 saat önce', createdAt: '2026-01-27T21:00:00Z', region: 'Girne', propertyType: 'Apartment', budget: 150000, currency: 'GBP', utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'search', consentKvkk: true },
    { id: 'l3', externalLeadId: 'tiktok_01', name: 'Alper Yılmaz', email: 'alper@yandex.com', phone: '+90 544 111 2233', leadSource: 'TikTok', campaignName: 'Modern Life', adSetName: 'Video A', adId: 'ad_03', formId: 'f_03', status: 'new', time: '3 saat önce', region: 'Iskele', propertyType: 'Residence', budget: 3500000, currency: 'TL', utm_source: 'tiktok', utm_medium: 'paid', utm_campaign: 'modern', consentKvkk: true },
    { id: 'l4', externalLeadId: 'meta_04', name: 'Emily Wilson', email: 'emily.w@me.com', phone: '+44 7911 123456', leadSource: 'Meta Ads', campaignName: 'Invest in Cyprus', adSetName: 'Europe Investors', adId: 'ad_04', formId: 'f_01', status: 'new', time: '5 saat önce', region: 'Lefkoşa', propertyType: 'Apartment', budget: 120000, currency: 'GBP', utm_source: 'instagram', utm_medium: 'paid', utm_campaign: 'invest', consentKvkk: true },
    { id: 'l5', externalLeadId: 'google_05', name: 'Mehmet Öz', email: 'm.oz@gmail.com', phone: '+90 533 222 3344', leadSource: 'Google Ads', campaignName: 'Bodrum Villaları', adSetName: 'Yüksek Gelir', adId: 'ad_05', formId: 'f_02', status: 'new', time: '8 saat önce', region: 'Bodrum', propertyType: 'Villa', budget: 12000000, currency: 'TL', utm_source: 'google', utm_medium: 'search', utm_campaign: 'bodrum_luxury', consentKvkk: true },
    { id: 'l6', externalLeadId: 'meta_06', name: 'David Brown', email: 'david.b@outlook.com', phone: '+44 7800 112233', leadSource: 'Meta Ads', campaignName: 'Sea View Properties', adSetName: 'Beach Lovers', adId: 'ad_06', formId: 'f_01', status: 'new', time: '12 saat önce', region: 'Girne', propertyType: 'Villa', budget: 300000, currency: 'GBP', utm_source: 'fb', utm_medium: 'paid', utm_campaign: 'seaview', consentKvkk: true },
    { id: 'l7', externalLeadId: 'tiktok_07', name: 'Selin Arı', email: 'selinari@gmail.com', phone: '+90 542 333 4455', leadSource: 'TikTok', campaignName: 'Resort Living', adSetName: 'Young Professionals', adId: 'ad_07', formId: 'f_03', status: 'new', time: '1 gün önce', region: 'İskele', propertyType: 'Apartment', budget: 4500000, currency: 'TL', utm_source: 'tiktok', utm_medium: 'paid', utm_campaign: 'resort', consentKvkk: true },
    { id: 'l8', externalLeadId: 'meta_08', name: 'Alex Carter', email: 'alex.c@gmail.com', phone: '+44 7722 334455', leadSource: 'Meta Ads', campaignName: 'Luxury Penthouses', adSetName: 'High Net Worth', adId: 'ad_08', formId: 'f_01', status: 'new', time: '1 gün önce', region: 'Girne', propertyType: 'Penthouse', budget: 450000, currency: 'GBP', utm_source: 'ig', utm_medium: 'paid', utm_campaign: 'luxury_pent', consentKvkk: true },
    { id: 'l9', externalLeadId: 'google_09', name: 'Hülya Koç', email: 'h.koc@mynet.com', phone: '+90 535 444 5566', leadSource: 'Google Ads', campaignName: 'Search - Investment', adSetName: 'Real Estate ROI', adId: 'ad_09', formId: 'f_02', status: 'new', time: '1 gün önce', region: 'Gazimağusa', propertyType: 'Plot', budget: 2000000, currency: 'TL', utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'roi_invest', consentKvkk: true },
    { id: 'l10', externalLeadId: 'meta_10', name: 'James White', email: 'james.white@uk.com', phone: '+44 7855 667788', leadSource: 'Meta Ads', campaignName: 'Villa Dreams', adSetName: 'Pensioners', adId: 'ad_10', formId: 'f_01', status: 'new', time: '2 gün önce', region: 'Bafra', propertyType: 'Villa', budget: 250000, currency: 'GBP', utm_source: 'fb', utm_medium: 'paid', utm_campaign: 'retire', consentKvkk: true },
    { id: 'l11', externalLeadId: 'tiktok_11', name: 'Canberk Yalçın', email: 'canb@gmail.com', phone: '+90 530 555 6677', leadSource: 'TikTok', campaignName: 'Studio Life', adSetName: 'Students/Young', adId: 'ad_11', formId: 'f_03', status: 'new', time: '2 gün önce', region: 'Lefkoşa', propertyType: 'Studio', budget: 1500000, currency: 'TL', utm_source: 'tiktok', utm_medium: 'paid', utm_campaign: 'studio', consentKvkk: true },
    { id: 'l12', externalLeadId: 'google_12', name: 'Linda Moore', email: 'linda.m@hotmail.com', phone: '+44 7733 445566', leadSource: 'Google Ads', campaignName: 'Cyber Property Search', adSetName: 'Expat Living', adId: 'ad_12', formId: 'f_02', status: 'new', time: '3 gün önce', region: 'Girne', propertyType: 'Apartment', budget: 180000, currency: 'GBP', utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'expat_search', consentKvkk: true }
];
